### ISSUE TITLE
Why ban functionalstorage's fluid drawer！

### ISSUE THREAD

**Issue by 3453890470** [trulyno/star-technology#10]
I love it, but I can't get it!!!

**Comment by trulyno** [comment]
I wanted to encourage the usage of gregtech drums

**Comment by 3453890470** [comment]
Or does it make fluid storage cheap and not fit your production philosophy?

**Comment by trulyno** [comment]
I added functional storage only for the item drawers. I limited them to only copper upgrades. Drawers are really powerful, for that reason people will use them and not other storage solutions. I want to encourage the usage of gregtech storage solution. As for fluid drawers, I don't seethe point of them. They have low capacity, and although the can be connected to a network, that feature will be used very little. At least that is the case for me.

**Comment by 3453890470** [comment]
The upgrade makes the fluid drawer powerful, but the copper upgrade only has 32B*4^4 capacity (8192B), which is a pity, and perhaps should be appropriately opened up for higher level upgrades. Ouch! You almost convinced me, but I like fluid drawers. I don't need a reason.

**Comment by 3453890470** [comment]
I feel a little confused, maybe I think too much.

**Comment by trulyno** [comment]
If you want to use fluid drawers, I'm not stopping you. You'll have to look in the kubejs scripts where to enable them. But I won't allow higher tier upgrades as I do want to encourage the usage of gregtech storage solutions.

**Comment by Zebrix** [comment]
Maybe just make higher tier updates expensive, for example crafting from GT supertanks@chests? )
In general, particularly large containers are not really needed; it’s just a shame to throw away excess resources...
