### ISSUE TITLE
some quest book issues

### ISSUE THREAD

**Issue by Hozzzd** [trulyno/star-technology#100]
# LV:
* the neodymium magnet check isn't optional and it requires the neodymium dust check from nuclear fission, which is only unlocked after prometheum-147 (its not accessible before reaching EV and makes completing lv before then impossible)
---
# MV:
* the tree greenhouse controller, while convenient, is more expensive and slower than the mechanical bearing tree chopping setup from create in mv and as such should be placed in hv or made optional; the same goes for thermal's upgrade kits (water wheel or steam engine spam for carbon brushes is viable up until IV) and the electric jetpack (jet boots in the shop are plain better)
---
# EV:
* kanthal coils on the electric blast furnace are needed to make silicon ingots way before EV for basic transistors and ae2 circuits so they belong in mv
* the optional nuclear reactor placed right after the vacuum freezer doesn't have a recipe and is impossible to craft, making the **not** optional (and uncraftable) nuclear turbine impossible to complete, locking ev's completion

**Comment by Caerglad** [comment]
Quests are going to be reworked in future updates
