### ISSUE TITLE
fatal game crash when wrenching or placing shafts on the create diesel engine

### ISSUE THREAD

**Issue by JennaUwU** [trulyno/star-technology#101]
rarely when using the large diesel engine from create attached to the magnetic coils it will throw an error and crash the game 
[crash-2024-09-09_02.47.01-client.txt](https://github.com/user-attachments/files/16967117/crash-2024-09-09_02.47.01-client.txt)
[crash-2024-09-11_19.01.51-client.txt](https://github.com/user-attachments/files/16967120/crash-2024-09-11_19.01.51-client.txt)

**Comment by xanerin** [comment]
yeah same i keep having this issue specially when using the wrench or placing down shafts that are directly attached

**Comment by Caerglad** [comment]
wasn't able to reproduce it in 1.20 version, so after updating the pack it may get fixed
