### ISSUE TITLE
Crafting gives Brass Bolts

### ISSUE THREAD

**Issue by BeardBois** [trulyno/star-technology#11]
Hello!

Just starting your modpack. I have found that putting anything into crafting table then taaking it out gives 'brass bolts'. Attached is the video of it happening! Let me know if I can supply any more info!

https://github.com/trulyno/star-technology/assets/134227567/2be12940-f528-4e82-b41a-7d4697e78551

**Comment by trulyno** [comment]
This is a known issue. I don't know the cause, but if you rejoin the world or do a /reload it'll fix it
