### ISSUE TITLE
Server still starting, please wait before reconnecting

### ISSUE THREAD

**Issue by Joltified** [trulyno/star-technology#121]
After a while of playing, the server breaks and when people try to join it says server still starting, please wait before reconnecting. This has happened 3 times. The first time I had to reset the world, the second time i updated all of the mods, and now it happened again for the third time. I have experimented a lot with this, for some reason the world works in singleplayer fully, but in multiplayer, you have to delete a corrupted reigon file for the server to boot up properly. As I said before, I managed to somehow fix this by updating all the mods, so I dont think the problem is that my world is corrupted.

**Comment by trulyno** [comment]
There is not enough information to find the issue. Please look at the logs for any errors that could cause it.
Common world corruption causes in this pack are:
- Large Colossal chests
- NuclearCraft fission reactors

You can try loading a backup and removing any colossal chest.

**Comment by Joltified** [comment]
Thanks for the quick reply. When the server broke previously, I removed one of the chunk files not including a colossal chest or a fission reactor, and the server worked again, but ill try again.

**Comment by Joltified** [comment]
Yeah, I tried removing the colossal chest I have and the server still does not allow players to join, but it works in singleplayer.

**Comment by kjbissell** [comment]
I had similar issue where the server would end up timing out on a single tick.  Removing a campfire crucible lava setup was enough to fix my issue(I loaded up the save in single player, removed the setup and put the world back on the server). I can't find the crash report that pointed me at this, but I think it was a dead lock when trying to compute the lighting.

**Comment by LeDiablePatate** [comment]
Try to remove Starlight
