### ISSUE TITLE
Missing mods from Cursed launcher

### ISSUE THREAD

**Issue by Odditiescollector** [trulyno/star-technology#138]
[crash-2024-11-10_15.37.14-fml.txt](https://github.com/user-attachments/files/17692007/crash-2024-11-10_15.37.14-fml.txt)

i downloaded star technology on cursed and after allocating 8gb to the game upon launching it says 14 mods are not installed

**Comment by trulyno** [comment]
are you using tlauncher or something? the only reason for this is that you are not installing the pack correctly via a proper minecraft launcher like curseforge or prism

**Comment by Odditiescollector** [comment]
i downloaded the mod pack via cursed forge launcher and i was getting this

**Comment by trulyno** [comment]
try downloading it again

**Comment by Odditiescollector** [comment]
will do, i'll let you know here what happens once i launch it after download ( honestly no idea why  this happened but figured i'd ask you)

**Comment by Odditiescollector** [comment]
it seems to have installed properly this time around as i can make and load a new sky block world
