### ISSUE TITLE
game instantly crash while opening

### ISSUE THREAD

**Issue by MiniQsERcE** [trulyno/star-technology#140]
[crash-2024-11-12_11.45.41-client.txt](https://github.com/user-attachments/files/17713626/crash-2024-11-12_11.45.41-client.txt)
[2024-11-12-6.log](https://github.com/user-attachments/files/17713627/2024-11-12-6.log)
i'm just dont know what to do

**Comment by Caerglad** [comment]
Did you changed anything in the modpack?

**Comment by trulyno** [comment]
Looking at the log, it's a bug i encountered before that appears randomly. I recommend you reinstall the pack
