### ISSUE TITLE
Tree Greenhouse Controller MultiBlock is broken 

### ISSUE THREAD

**Issue by AzzyDR** [trulyno/star-technology#148]
i cant get the Tree greenhouse Controller to form at all the multiblock seems to be broken i gonna add botany pots (with tweaked Values) or a alterenative for the time being until it is fixed

**Comment by UltraPuPower** [comment]
if you could open a ticket here [Discord](https://discord.com/channels/1177211394039484477/1254848063021776987) and show some screenshots we could try to fix it. You are most likely doing something wrong, as there are no others who have reported this behaviour.

**Comment by AzzyDR** [comment]
its been fixed it was a chunk border issue it was in 4 chunks at the same time
