### ISSUE TITLE
Crash after accessibility onboarding

### ISSUE THREAD

**Issue by Ash-Forest** [trulyno/star-technology#149]
Downloaded pack via Prism Launcher on NixOS. 

Attempted to reinstall the pack and issue persists.

Following the accessibility screen the game immediately crashes. Attempting to launch the game after this crash bypasses the accessibility screen but will still crash before main menu is displayed.

[crash-2024-11-18_18.47.12-client.txt](https://github.com/user-attachments/files/17807458/crash-2024-11-18_18.47.12-client.txt)
[debug.log](https://github.com/user-attachments/files/17807485/debug.log)

**Comment by trulyno** [comment]
Remove the folowing mods: WebDisplays, MCEF

**Comment by Ash-Forest** [comment]
That resolved the issue. Thank you.
