### ISSUE TITLE
Error when trying to Load to Main Menu in AT Launcher

### ISSUE THREAD

**Issue by Retr0Spec-dev** [trulyno/star-technology#150]
![image_2024-11-19_150128220](https://github.com/user-attachments/assets/79326d97-6caa-467b-9934-41a08d7eb415)

Updated from 1.20.1 - GAMMA HOTFIX 3 [Working] TO 1.20.1 - DELTA [This Issue]

No clue why.. any ideas?

**Comment by GregtechEnjoyer** [comment]
make a new instance
