### ISSUE TITLE
Wrong block created by using easy cobblestone generator in questline

### ISSUE THREAD

**Issue by Riki2022** [trulyno/star-technology#151]
in the new Delta version, putting lava on top of a water filled stone barrel create an air block instead of a cobblestone

**Comment by LordErelis** [comment]
Version: Star Technology-1.20.1-DELTA
On single and multiplayer servers stonebarrel filled with water and lava placed above will stop generating cobblestone after removing the cobblestone via a hopper resulting into Air being generated instead.
For multi-/singleplayer a server restart will result into cobblestone being generated again until removal via hopper

EDIT:
The bug only appears when the hopper pulling the generated cobblestone from the barrel becomes empty
Replacing hopper/barrel/lava in the same or another location nor building another cobblegenerator of this type will result into cobblestone being generated unless the server is being restarted reloading also does not help

In case this does help to understand the problem, some footage of my (short) testing 
(i repeated the same testing on a multiplayer server with the same result):
https://youtu.be/7weP3hh-vn4

**Comment by stellaurora** [comment]
This is a bug with the ex nihilo mod, i believe related to

https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/471

**Comment by trulyno** [comment]
fixed in delta hotfix 1

**Comment by JesperKuipers** [comment]
> fixed in delta hotfix 1
its not, got the issue on 1.20.1-DELTA-HOTFIX-1.zip
