### ISSUE TITLE
Thermal Cultivation Tomato Recipe Issue

### ISSUE THREAD

**Issue by ryleu** [trulyno/star-technology#153]
Using Thermal Cultivation's tomatoes in a GregTech large farm yields only tomato seeds. The Farmer's Delight tomato farming recipe also yields tomatoes, but Farmer's Delight tomatoes cannot be obtained as far as I can tell.

**Comment by ryleu** [comment]
Additionally, there is no way to craft Thermal Cultivation seeds from tomatoes.

**Comment by ryleu** [comment]
![image](https://github.com/user-attachments/assets/444e9877-c196-4584-bd07-bcbfac92da9f)
![image](https://github.com/user-attachments/assets/809105b5-8979-4eba-b347-a70615499534)

**Comment by trulyno** [comment]
uh i thought we fixed that a long time ago. will be fixed in epsilon

**Comment by trulyno** [comment]
fixed in delta hotfix 4
