### ISSUE TITLE
Low-heated Recipe Issues

### ISSUE THREAD

**Issue by ryleu** [trulyno/star-technology#154]
The low-heated recipe for cooked rice does not accept thermal cultivation rice: 
![image](https://github.com/user-attachments/assets/a1a6401f-c55a-47da-ae2e-90c3578860a9)

**Comment by UltraPuPower** [comment]
not an issue, this is a mod recipe, if you want it to change report it to the mod.

**Comment by trulyno** [comment]
this pack is designed to be played on peaceful, that is why food recipes go under the radar. We don't see this requiring immediate fixing. We will keep it in mind and change things around for it to work next major version(epsilon)

**Comment by ryleu** [comment]
Gotcha, I didn't realize that. I went ahead and opened an issue on create low heated, so hopefully by the time epsilon comes out it'll be fixed.
