### ISSUE TITLE
Basic Steam Turbine recipe consumes steam to produce destilled water. But water isn't produced

### ISSUE THREAD

**Issue by VladParshin** [trulyno/star-technology#156]
A simple setup: Create Copper tank with steam -> Basic Steam Turbine. Steam is consumed, but no water is output to be reused.

Recipe in Steam Turbine says 640mB of steam converts to 4mB of destilled water, which I was planning to feed back into the solar boilers.

**Comment by GregtechEnjoyer** [comment]
also the recipe you see only works in The steam turbine multiblock
