### ISSUE TITLE
Ex Nihilo Sequentia Hammer need soul infused rods to craft, Impossible to progress past the hammer quest.

### ISSUE THREAD

**Issue by AlexendreC** [trulyno/star-technology#157]
All the hammer of Ex Nihilo Sequentia need Soul infused rod to be craft making it impossible to progress. What i can see from DELTA-HOTFIX1 is that all hammer have the recipe with the forge:rods tag in the craft so making it possible with wood stick but in the DELTA-HOTFIX2 the recipe only have soul infused rod and the forge:rods tags dissapear.

**Comment by UltraPuPower** [comment]
should be fixed now, hotfix soon
