### ISSUE TITLE
Cutting Board (Framers Delight) + Gravel = Softlock

### ISSUE THREAD

**Issue by JenoYT1337** [trulyno/star-technology#158]
I was trying to get flint by using the Cutting Board from Framers Delight and a wooden shovel, and the game forced me into a weird pov and i cant interact with any of the overworld. I have tried to quit to title and reloading but im stuck in that same "softlock" pov.
![SC Gravel bug](https://github.com/user-attachments/assets/a1e11729-bd96-4e3c-b6fa-8872f378d886)

**Comment by trulyno** [comment]
it must be a bug with farmer's delight. please report it there. we can't do anything about it
