### ISSUE TITLE
Stone Barrel - Cobblestone generation not functional

### ISSUE THREAD

**Issue by geduardcatalindev** [trulyno/star-technology#161]
Stone Barrel Cobblestone generation does not work.

The Barrel only fills with water when I right-click on it but no Cobblestone is generated.

![image_2024-11-22_140916281](https://github.com/user-attachments/assets/c919872e-10de-4f18-a61a-230fa87ff99d)

**Comment by trulyno** [comment]
Update your pack. It was fixed

**Comment by geduardcatalindev** [comment]
I'm on Delta Hotfix 3 already.

**Comment by geduardcatalindev** [comment]
Odd thing I found is that is only working once when I restart the server (or client), meaning it generates one Cobblestone when I right-click on the barrel to fill it up with water but when I do it a second+time, it does not work.

**Comment by trulyno** [comment]
This should have fixed it https://github.com/trulyno/star-technology/commit/d6506a5609ea4b7d6cf770a24432154875eff2f4

**Comment by geduardcatalindev** [comment]
I can confirm that the "fix" is present in my files, both on the server and client but it's not working.

**Comment by trulyno** [comment]
then it is a mod issue. for now you can use the igneous extruder for auto cobble or a create cobble farm

**Comment by geduardcatalindev** [comment]
Is NeoForge and Forge fully compatible? Because I see that the mod is only for NeoForge for the current version of modpack Minecraft version so you had to use that.

**Comment by UltraPuPower** [comment]
it should be, I did testing
it also is not a universal issue, some people can't make cobble, but others can

**Comment by trulyno** [comment]
For people still experiencing this: dont use a hopper. use a chute. that seems to fix the issue
