### ISSUE TITLE
Smelting recipes make Nuclearcraft lead ingots

### ISSUE THREAD

**Issue by hhatcher** [trulyno/star-technology#162]
Running 1.20.1-DELTA-HOTFIX-3 and smelting recipes are creating lead ingots from NuclearCraft.  Tested with the multi-smelter, create bulk smelting, and the electric furnace from gregtech.

**Comment by hhatcher** [comment]
To clarify, I was using lead dust for all of these.

**Comment by Peap1ant** [comment]
same as well as using silver dust
