### ISSUE TITLE
Thermal augment recipes in EMI do not match created items

### ISSUE THREAD

**Issue by hhatcher** [trulyno/star-technology#163]
The recipes in EMI for thermal augments (Auxiliary Reaction Chambers, Multi Cycle Injectors) do not match the actual created items.  This causes problems with AE2 autocrafts - waiting forever because the expected item is never returned, and being unable to craft later tiers. 
 This can be fixed by manually remaking the recipes with the created items, but it's a hassle.
 
 Happening in 1.20.1-DELTA-HOTFIX-3

**Comment by UltraPuPower** [comment]
Nothing we can do about it, the upgrade components use NBT data, and we have not yet found a way to apply that on item creation rather then item crafting.
Believe me when I say the moment I figure it out it will happen.

**Comment by trulyno** [comment]
in delta the augments are all custom items rather than existing items. it is not a issue. please bear with it and update your recipes
