### ISSUE TITLE
Game crash.

### ISSUE THREAD

**Issue by benthejunglecat** [trulyno/star-technology#166]
Every time I try to open my world my game gets stuck in-between loading the spawn chunks and reading the world data, when I check the logs I see that my game crashed. I'm also using prism launcher
[crash-2024-11-23_00.23.59-server.txt](https://github.com/user-attachments/files/17878903/crash-2024-11-23_00.23.59-server.txt)

**Comment by trulyno** [comment]
hmm there is no hint of the cause in that log
