### ISSUE TITLE
Can't upgrade any Thermal dynamos, flux cells or fluid cells.

### ISSUE THREAD

**Issue by berksedatk** [trulyno/star-technology#168]
I have this issue where I cannot put any of custom upgrades for Thermal blocks such as dynamos, flux cells or even fluid cells. The one that thermal provides works just fine but the ones that are added by kubejs dont work including LV upgrades. 

![image](https://github.com/user-attachments/assets/dc0d224c-7c9a-4366-b03e-86255f33603a)

**Comment by GregtechEnjoyer** [comment]
the ones from the creative inventory don´t work try bookmarking the ones for the crafting recipe and using emi to cheat them in

**Comment by berksedatk** [comment]
> the ones from the creative inventory don´t work try bookmarking the ones for the crafting recipe and using emi to cheat them in

thank you im closing this issue
