### ISSUE TITLE
NC recipe conflict

### ISSUE THREAD

**Issue by Schrubbls** [trulyno/star-technology#17]
![image](https://github.com/trulyno/star-technology/assets/8899590/82fd4f1a-9a7d-414b-8bac-0511e9351a82)

uranium LEU and HEU have almost the same recipe needs some circuits
:)

**Comment by Schrubbls** [comment]
`  event.recipes.gtceu.mixer('TBU')
        .itemInputs(`9x ${Th232}`)
        .itemOutputs('nuclearcraft:fuel_thorium_tbu')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LEU233')
        .itemInputs(`1x ${U233}`, `8x ${U238}`)
        .itemOutputs('nuclearcraft:fuel_uranium_leu_233')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HEU233')
        .itemInputs(`3x ${U233}`, `6x ${U238}`)
        .itemOutputs('nuclearcraft:fuel_uranium_heu_233')
        .duration(400)
        .EUt(250);
    
    event.recipes.gtceu.mixer('LEU235')
        .itemInputs(`1x ${U235}`, `8x ${U238}`)
        .itemOutputs('nuclearcraft:fuel_uranium_leu_235')
        .duration(400)
        .circuit(0)
        .EUt(250);

    event.recipes.gtceu.mixer('HEU235')
        .itemInputs(`3x ${U235}`, `6x ${U238}`)
        .itemOutputs('nuclearcraft:fuel_uranium_heu_235')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LEN236')
        .itemInputs(`1x ${Np236}`, `8x ${Np237}`)
        .itemOutputs('nuclearcraft:fuel_neptunium_len_236')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HEN236')
        .itemInputs(`3x ${Np236}`, `6x ${Np237}`)
        .itemOutputs('nuclearcraft:fuel_neptunium_hen_236')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LECM243')
        .itemInputs(`1x ${Cm243}`, `8x ${Cm246}`)
        .itemOutputs('nuclearcraft:fuel_curium_lecm_243')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HECM243')
        .itemInputs(`3x ${Cm243}`, `6x ${Cm246}`)
        .itemOutputs('nuclearcraft:fuel_curium_hecm_243')
        .duration(400)
        .EUt(250);

        event.recipes.gtceu.mixer('LECM245')
        .itemInputs(`1x ${Cm245}`, `8x ${Cm246}`)
        .itemOutputs('nuclearcraft:fuel_curium_lecm_245')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HECM245')
        .itemInputs(`3x ${Cm245}`, `6x ${Cm246}`)
        .itemOutputs('nuclearcraft:fuel_curium_hecm_245')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LECM247')
        .itemInputs(`1x ${Cm247}`, `8x ${Cm246}`)
        .itemOutputs('nuclearcraft:fuel_curium_lecm_247')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HECM247')
        .itemInputs(`3x ${Cm247}`, `6x ${Cm246}`)
        .itemOutputs('nuclearcraft:fuel_curium_hecm_247')

        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LEB248')
        .itemInputs(`1x ${Bk248}`, `8x ${Bk248}`)
        .itemOutputs('nuclearcraft:fuel_berkelium_leb_248')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HEB248')
        .itemInputs(`3x ${Bk248}`, `6x ${Bk247}`)
        .itemOutputs('nuclearcraft:fuel_berkelium_heb_248')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LECF249')
        .itemInputs(`1x ${Cf249}`, `8x ${Cf252}`)
        .itemOutputs('nuclearcraft:fuel_californium_lecf_249')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HECF249')
        .itemInputs(`3x ${Cf249}`, `6x ${Cf252}`)
        .itemOutputs('nuclearcraft:fuel_californium_hecf_249')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LECF251')
        .itemInputs(`1x ${Cf251}`, `8x ${Cf252}`)
        .itemOutputs('nuclearcraft:fuel_californium_lecf_251')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HECF251')
        .itemInputs(`3x ${Cf251}`, `6x ${Cf252}`)
        .itemOutputs('nuclearcraft:fuel_californium_hecf_251')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LEA242')
        .itemInputs(`1x ${Am242}`, `8x ${Am243}`)
        .itemOutputs('nuclearcraft:fuel_americium_lea_242')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HEA242')
        .itemInputs(`3x ${Am242}`, `6x ${Am243}`)
        .itemOutputs('nuclearcraft:fuel_americium_hea_242')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LEP239')
        .itemInputs(`1x ${Pu239}`, `8x ${Pu242}`)
        .itemOutputs('nuclearcraft:fuel_plutonium_lep_239')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HEP239')
        .itemInputs(`3x ${Pu239}`, `6x ${Pu242}`)
        .itemOutputs('nuclearcraft:fuel_plutonium_hep_239')
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('LEP241')
        .itemInputs(`1x ${Pu241}`, `8x ${Pu242}`)
        .itemOutputs('nuclearcraft:fuel_plutonium_lep_241')
        .circuit(0)
        .duration(400)
        .EUt(250);

    event.recipes.gtceu.mixer('HEP241')
        .itemInputs(`3x ${Pu241}`, `6x ${Pu242}`)
        .itemOutputs('nuclearcraft:fuel_plutonium_hep_241')
        .duration(400)
        .EUt(250);
`

**Comment by Schrubbls** [comment]
added to every L fuel a circuit 0

**Comment by trulyno** [comment]
Fixed in latest version
