### ISSUE TITLE
Komaru Cat quest cannot be cleared

### ISSUE THREAD

**Issue by RockemRobotics** [trulyno/star-technology#172]
The Quality of Life -> Komaru Cat repeatable quest cannot ever be fully cleared of its exclamation point. To complete the quest, you simply have to get a komaru powder in your inventory. On clearing the quest, one of the rewards is more komaru powder, which automatically clears the quest again for you. This effectively lets you get infinite komaru powder and infinite komaru spawn eggs, and makes sure the red exclamation point never clears.

**Comment by Caerglad** [comment]
based on discord replies
"You can claim the powder then put it away before claiming the spawn egg, this breaks the loop"

**Comment by RockemRobotics** [comment]
Thank you @Caerglad - I can't believe I hadn't thought of that. The only downside is now I can't ever put that komaru powder back in my inventory or I'll have completed the quest again.
