### ISSUE TITLE
Shift Right Clicking Grass gives infinite pebbles

### ISSUE THREAD

**Issue by manav907** [trulyno/star-technology#179]
Modpack version:  1.20.1-GAMMA-DELTA-HOTFIX-4
Minecraft version: 1.20.1 Forge
Is on server: yes
Modifications done: none
Description: if you shift right click on grass blocks with an empty hand you can get infinite pebble drops of various stones

is this intended?

**Comment by LeDiablePatate** [comment]
Of course it is ! Why wouldn't it be ?

**Comment by Caerglad** [comment]
It is, we are on sky-block
