### ISSUE TITLE
game fails to load

### ISSUE THREAD

**Issue by Bardmine4** [trulyno/star-technology#183]
Modpack version: 1.20.1 delta hotfix 4
Minecraft version: 1.20.1
Is on server:
Modifications done: 
Description:
game fails to finish loading and crashes after finishing loading saying ti fails to load a library,
crash log given below:
[crash-2024-12-03_18.33.06-client.txt](https://github.com/user-attachments/files/18001954/crash-2024-12-03_18.33.06-client.txt)

**Comment by trulyno** [comment]
It seems it's something related to WebDisplays. If the issue persists, it's best to remove the following mods: WebDisplays, MCEF

**Comment by Bardmine4** [comment]
> It seems it's something related to WebDisplays. If the issue persists, it's best to remove the following mods: WebDisplays, MCEF

that seems to have done the trick
