### ISSUE TITLE
[Recipe Addition] Functional Storage Puller/Pusher QoL

### ISSUE THREAD

**Issue by Ianthasys** [trulyno/star-technology#185]
Another QoL addition I'd thought of is a means to swap between puller upgrades and pusher upgrades due to them requiring the same materials to craft, but the crafting recipe is just inverted. Adding a recipe like this will help in early game so that if people tear down farms that use them, they can reuse the upgrades in either form. 

Here is the example recipe that I'm using in my personal KubeJS modifications file in `startup_scripts`
```js
ServerEvents.recipes(event => {
    event.shapeless(
        Item.of('functionalstorage:puller_upgrade'),
        ['functionalstorage:pusher_upgrade']);
    event.shapeless(
        Item.of('functionalstorage:pusher_upgrade'),
        ['functionalstorage:puller_upgrade']);
});
```

**Comment by ssoaper** [comment]
You put the ignoreNBT on the output stack lol, otherwise looks good.

**Comment by Ianthasys** [comment]
that probably explains why it wasn't showing up, though crafting it worked fine either way
