### ISSUE TITLE
Skill Issue: Lock recipes behind progression

### ISSUE THREAD

**Issue by PoXel69** [trulyno/star-technology#187]
Description:
Why you think this will fit well in the modpack: 
Hi, newbie here
I haven’t played any GT packs or many modpacks in general, so when I started playing Star-Technology, I found it very overwhelming to figure out what to do and how to progress.

For example, I still don’t know how to make "Silicon Dust." Oh, it’s in the processing line after "Flint Dust" and "Silicon Dioxide Dust." Wait—don’t you need "Silicon" to oxidize it?

Anyway, there are 10 different methods in EMI to make "Silicon Dioxide Dust," but the most straightforward one involves the Solid Blast Furnace. However, that process requires "Silicon" to work. And guess what? You can make "Silicon" in a Centrifuge using 10 Redstone Dust (which takes 64 seconds).

So why is "Silicon" placed after "Silicon Dioxide Dust" in the processing line quests tab if you can actually make it first and then use it to create "Silicon Dioxide Dust"?

From what I’ve heard about GregTech, I assume this is normal, but I’d like to request that the quests be structured more like a guide. 
And lock the recipes that are not used in Beginning behind a Progression level.

Again, I don't blame it on modpack, it is purely skill issues.

**Comment by UltraPuPower** [comment]
To answer the question: "So why is "Silicon" placed after "Silicon Dioxide Dust" in the processing line quests tab if you can actually make it first and then use it to create "Silicon Dioxide Dust"?", the answer is this: this certain line processes items, and the first result you get is silicon dioxide. This does not mean you can't go the other way, but it means that in this chain of recipes, it gets made before normal silicon. 
The quests are structured like a guide, are you perhaps looking at the wrong chapters? They take you through the entire pack, just look at the chapters in the Progression category (the first one is early game). 
Locking recipes is not a good solution in my eyes, but maybe other developers differ on this stance.

**Comment by PoXel69** [comment]
that makes sense to me, i guess
Thanks
