### ISSUE TITLE
QoL mod request

### ISSUE THREAD

**Issue by PoXel69** [trulyno/star-technology#188]
Description:
Why you think this will fit well in the modpack: 
- Elevator mod
- Crafting on a stick(which can be used in a a curio slot) 
- Sophisticated backpack & storage

### Why is Elevator mod needed?
Vertical movement is a nightmare with water or scaffolding, this mod will improve that

### Why is Crafting on a Stick mod needed?
Easier crafting duh

### Why is Sophisticated Storage/Backpacks mods needed?
Great early to mid game storage solution and the backpacks are unbelievably good  with great upgrades

[Elevator mod's Curse-Forge page](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Crafting on a Stick's Curse-Forge page](https://www.curseforge.com/minecraft/mc-mods/crafting-on-a-stick)
[Sophisticated Backpack's Curse-Forge page](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Sophisticated Storage's Curse-Forge page](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)

**Comment by LeDiablePatate** [comment]
Elevator mod : Travel anchors already do that
Crafting on a Stick : This is a skyblock without any exploration (yet)
Sophisticated Storage/Backpacks : There is already Colossal Chests

**Comment by PoXel69** [comment]
> Elevator mod : Travel anchors already do that
i wouldn't say that, Travel anchors add more clutters to inventory(the wand) which imo is against the point of a QoL
but yeah i over looked them for being a elevator

> Crafting on a Stick : This is a skyblock without any exploration (yet)
you say cause it is a skyblock i have to keep running at my crafting table and back to make a item or multiblock

> Sophisticated Storage/Backpacks : There is already Colossal Chests
yes Colossal Chest are pretty good for storage
but backpacks make a huge difference, simply backpacks just are too simple

but if it's not convincing Close the issue
Thanks for your time

**Comment by trulyno** [comment]
1. You can make elevators with create. But the main reason is that you unlock jetboots early MV so there is no point to elevators aside from aesthetics
2. Most people have a centralized storage system. Use Tom's Storage System and you will have a storage + crafting system. It's cheap and very early.
3. Sophisticated storage/backpacks is way to powerful and hard to tweak. There are plenty of storage solutions already in the pack as well as a backpack mod. But, considering how you unlock AE2 in it's entirety at mid-MV, there is no point to even use a backpack, especially if you already use Tom's.

**Comment by PoXel69** [comment]
Makes sense,
Thanks for your time.
