### ISSUE TITLE
Netherrite unobtainable

### ISSUE THREAD

**Issue by Schrubbls** [trulyno/star-technology#19]
Machine prefers to use the circuitless recipe instead of the circuit

![image](https://github.com/trulyno/star-technology/assets/8899590/86e13c1d-1859-47ac-adb9-bf0ae2666ec5)

Maybe change the recipe to Nether Agglomeratio

**Comment by trulyno** [comment]
GT machines should prioritize circuit recipes. When I tested, it worked. If it doesn't work it's gtceum's fault
