### ISSUE TITLE
Thermalpedia Recipe Conflict

### ISSUE THREAD

**Issue by Zatone0** [trulyno/star-technology#191]
Modpack version: 1.20.1-DELTA-HOTFIX-4
Minecraft version: 1.20.1
Is on server: Pack side
Modifications done: None
Description: When crafting a thermal series wrench the recipe defaults to the hammerlib wrench which prevents the creation of the thermalpedia.
Suggestion: This isn't the only recipe to have conflicts, add in [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph) to prevent multi recipe interactions like this, the main one is small vs tiny piles of every dust.

**Comment by ssoaper** [comment]
Small and tiny piles of dust aren't a conflict. Wrench conflict is also fixed in the github version.
