### ISSUE TITLE
Changing Gems to crushed variants

### ISSUE THREAD

**Issue by Schrubbls** [trulyno/star-technology#2]
`    sieve('flint', 0.1, sand, 'gtceu:green_sapphire_crushed:ore', false);
    sieve('flint', 0.1, sand, 'gtceu:sapphire_cushed_ore', false);
    sieve('flint', 0.1, sand, 'gtceu:ruby_crushed_ore', false);
    // sieve('flint', 0.1, sand, 'gtceu:raw_opal', false);
    sieve('flint', 0.1, sand, 'minecraft:coal', false);
    sieve('flint', 0.1, sand, 'gtceu:quartzite_crushed_ore', false);
    sieve('flint', 0.1, sand, 'gtceu:certus_quartz_crushed_ore', false);
    sieve('flint', 0.1, sand, 'gtceu:salt_crushed_ore', false);
    sieve('flint', 0.1, sand, 'gtceu:rock_salt_crushed_ore', false);
    sieve('flint', 0.1, sand, 'gtceu:saltpeter_crushed_ore', false);
    sieve('flint', 0.1, sand, 'gtceu:realgar_crushed_ore', false);`

I would change the Gems to crushed gems, due to more uses for them this way you could easily use the sifter block from GT:M since they are pretty much not used.

Also it gives access to vanadium since there is no way to get it.

With the crushed ore you can make ruby/green and blue sapphire slurry to get a source of Vanadium.

(Vanadium is required to cut silicon boule since it requires an MV cuttingmachine which requires vanadium steel blade)

**Comment by trulyno** [comment]
I had forgotten about vanadium

**Comment by Schrubbls** [comment]
> I had forgotten about vanadium

no worries this is why i test stuff xD
