### ISSUE TITLE
Issue Report

### ISSUE THREAD

**Issue by PrzemyslawRawski** [trulyno/star-technology#203]
Modpack version: 1.20.1 hotfix 4
Minecraft version:1.20
Is on server:no
Modifications done: nothing
Description:
Tin liquid temp is 505k but for all recepies you need 1258k so you cant go past electric blast furnace
![Zrzut ekranu 2024-12-23 074634](https://github.com/user-attachments/assets/2d0a80cf-56e2-4f97-a582-37895468d14e)
![Zrzut ekranu 2024-12-23 074759](https://github.com/user-attachments/assets/b1d537e5-ef65-4000-a91a-d0312a4d07ce)

**Comment by KillLaAqua** [comment]
Please read carefully those are 2 different liquids
