### ISSUE TITLE
Quests not working

### ISSUE THREAD

**Issue by PrzemyslawRawski** [trulyno/star-technology#204]
Modpack version: 1.20.1 hotfix 4
Minecraft version:1.20
Is on server:no
Modifications done: nothing
Description:
i have done all early game quests but only 4 of them are complited. I was trying to restart game when i have needed items in eq but nothing is working. Those 4 quests take a long time to be complited dont know how. Worth mention is i have enabled cheating
![Zrzut ekranu 2024-12-23 080150](https://github.com/user-attachments/assets/8788f528-4932-46ad-98ff-e3e4418ffe7a)
![Zrzut ekranu 2024-12-23 080130](https://github.com/user-attachments/assets/acc49a21-4e62-43f5-9c3f-1c140a822eda)
![Zrzut ekranu 2024-12-23 080340](https://github.com/user-attachments/assets/9b34fc3d-b27a-4dfd-80b5-d7bc63d24e93)

**Comment by PrzemyslawRawski** [comment]
also opening early game tab freeze minecraft for few seconds

**Comment by KillLaAqua** [comment]
Use your eyes please, you have not clicked the starter quest. This is ENTIRELY user error. Though may be force fixed in the future.
