### ISSUE TITLE
"Lore" Quest Spelling and Grammer Errors

### ISSUE THREAD

**Issue by extra-ordinary** [trulyno/star-technology#26]
Sorry, I didn't want to fork the repo just to make this.

Problem: "Lore" quest has many spelling errors and some grammar stuff that could be better.

Here is my corrected description of the quest:
>Red screens flash and alarms are going off. Everyone in the room is evacuating. The experiment is a failure. There is little time before the building explodes. But you notice something... the gate ... is opening! You stare in awe and think, "Yes! My theories were right! I figured out what the problem was!". You don't notice the others calling out to you to run. But it was too late; a failure is still a failure and the gate engulfs everything in the room.

>You wake up stranded on a floating island in an alternate dimension. The only things you have is a tree, a water source and some plants. But you are not discouraged. As the world's greatest scientist you can use these materials to develop technology at faster rate than anyone. You can try once again inter-dimensional travel. For that you will have to make from almost nothing everything, to develop up to draconic and even star technology. You &oWILL&r succeed. You &oWILL&r return home.

>&lWelcome to Star Technology.&r

**Comment by trulyno** [comment]
Thanks. I'll be adding it
