### ISSUE TITLE
Brick Wooden Frame gets consumed in crafting table

### ISSUE THREAD

**Issue by Scornexon** [trulyno/star-technology#28]
I discovered that the brick wooden frame gets consumed in the crafting table and there for i would have to create 39 frames to create one coke oven.

I'm playing on the beta 5 hotfix 3 version.

I dont know if you need more informations, but i'm happy to provide more.

**Comment by trulyno** [comment]
That is not an issue with star technology, it is gtceum's issue. I've fowarded it to the gtceum devs. They say it'll be fixed soon.

**Comment by Scornexon** [comment]
Oh okay, i played another Modpack with gtceum and the frame was not cosumes, so i thought it hat to do with this modpack.
Never mind than for the issue and thanks for forwarding it to the gtceum devs.

Have a nice day.
