### ISSUE TITLE
FTB Quests 1902.5.0+ Requires FTB XMod Compat 

### ISSUE THREAD

**Issue by JoBanJo** [trulyno/star-technology#38]
FTB Quests 1902.5.0+ requires the mod FTB XMod Compat for KubeJS, JEI, REI or Game stages integration with FTB Quests. 

You can see this requirement stated on the FTB Quests Curseforge page. 
https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge

**Comment by trulyno** [comment]
I looked at the page and it's not a 'requirement' but more of a suggestion if you want better compatibility. Had it been a requirement, it would've had installed automatically.
But regardless of phrasing, I will add it in next update. Next time you make a suggestion, please use a more polite and less demanding language, as it makes me(or whoever you suggest it to) be less willing to add your suggestion.

**Comment by JoBanJo** [comment]
> I looked at the page and it's not a 'requirement' but more of a suggestion if you want better compatibility. Had it been a requirement, it would've had installed automatically. But regardless of phrasing, I will add it in next update. Next time you make a suggestion, please use a more polite and less demanding language, as it makes me(or whoever you suggest it to) be less willing to add your suggestion.

I'm sorry I misread it as a requirement.

**Comment by trulyno** [comment]
No problem. Just be careful in the future. But the suggestion is really helpful
