### ISSUE TITLE
Modpack server

### ISSUE THREAD

**Issue by Lucas-Pardo** [trulyno/star-technology#40]
Hello, I played the modpack for a little bit and it seems awesome. I would like to play with a friend but I see that there are no server files. I have seen your instructions in the questbook to create a server and I have done it before but it is giving me errors for some reason. I manually deleted oculus and panorama as you said but it was still giving me the message "Zume failed to load", so I manually added Zume to mods and now the message I am getting is:

![image](https://github.com/trulyno/star-technology/assets/107495790/1b927e77-cbd9-4e4a-8013-1d7e3108c70a)

![image](https://github.com/trulyno/star-technology/assets/107495790/6d5b1f16-d7fd-46af-a5d0-f446d4f570a1)

Could you help me identify the problem? Thank you for the help and good job with the modpack, one of the best new greg modpacks I have seen, can't wait to play it.

**Comment by trulyno** [comment]
Hi. I plan to add server files when the full release will come, but I'm considering adding server files starting with next update.
The error you are seeing is from the Zalloy custom coil. For some reason, servers do not like custom coils. Removing it will let the server start. Here are the instructions to do so:
1) Navigate to the kubejs folder
2) Go to startup_events and open "custom blocks and items.js"
3) Comment out the lines 298-307(to comment it out add a /* before it and a */ after it.
4) No go to server_events/endgame content and open "recipes.js"
5) Comment out the lines 331-336(also using /* and */
Now start the server. You might also need to remove any client side mods like embeddium, embeddium++, mouse tweaks and FPS reducer.
Keep me updated if you encounter other problems.

**Comment by Lucas-Pardo** [comment]
Thank you for the quick response, that worked. Although it creates a normal world (not skyblock), do you know how to change that? Just curious, for now I solved it by copying a singleplayer generated world to the server.

**Comment by stellaurora** [comment]
> Thank you for the quick response, that worked. Although it creates a normal world (not skyblock), do you know how to change that? Just curious, for now I solved it by copying a singleplayer generated world to the server.

You can change `level-type` in server.properties to `mcskyblock\:skyblock` such that

`level-type=mcskyblock\:skyblock`

**Comment by Lucas-Pardo** [comment]
Oh, nice, thank you very much.

**Comment by trulyno** [comment]
Defaultworldtype doesn't seem to work automatically on the server. That is why in server.properties that is needed

**Comment by Lucas-Pardo** [comment]
Inside the server world it says this on the chat:

![image](https://github.com/trulyno/star-technology/assets/107495790/3d2c81ca-a7c8-46e6-a453-30e04cfbb69a)

It seems like there is an error with the tree greenhouse. I checked on JEI and there is no recipe for the controller and it only shows a single recipe for this multiblock (oak logs). I don't know if that is fine (I would've thought there would be a recipe for each type of log). Not a problem for now since I am just starting the pack but I thought it would be good to let you know. Again, thanks for the help. Everything else seems to be working fine, I'll let you know if I find more things missing in the server.

**Comment by trulyno** [comment]
Ok so go to kubejs/server_events/multiblock_recipes/tree_greenhouse.js
Everywhere you see CO2 and NPK with capital letters, replace those with lower case letters(co2 and npk)

**Comment by Lucas-Pardo** [comment]
Perfect, it worked, all fixed. Thanks.
