### ISSUE TITLE
Crash on viewing Multiblock data in JEI

### ISSUE THREAD

**Issue by Dejojotheawsome** [trulyno/star-technology#46]
As the title says, when attempting to view the multiblock data in JEI the game crashes

Pastebin of crash report: https://pastebin.com/apx9755N

**Comment by trulyno** [comment]
That is not issue of the modpack, it's an issue betwen gt and JEI. To avoid it, just be in fullscreen when viewing and/or with smaller GUI

**Comment by Dejojotheawsome** [comment]
Ah understood! Thank you!
