### ISSUE TITLE
Attempting to craft the redstone servo instead makes the redstone dust cover facade BETA 10 HOTFIX 4

### ISSUE THREAD

**Issue by Vormiam** [trulyno/star-technology#53]
I shift click the redstone servo recipe into the crafting table with EMI, it's exactly as it's supposed to be, but it has the redstone dust cover facade as the output for whatever reason. It stays as the output even if I remove three of the redston dusts, however it disapears if I take all four away or if I take any of the three iron plates away. EMI says the recipe for that item is supposed to be three plates and stone in a mixer for automated shapless crafting. My best guess is that redstone dust is tagged as "stone" and therefore works with the recipe, however I'm not sure why it still works even with more than one redstone present, why it's recipe overwrites the servo recipe, or why it can be crafted at a crafting table when EMI only shows it's recipe in a mixer.

If it's relevant, I have added other mods for the sake of performance and convienence, they are the following:
Compact Machines
Crafting Tweaks
Fastworkbench
Fastfurnace
Fastsuit
Dank Storage
Entangled
Openblocks elevator
Super Factory Manager
Tool Belts

I have attempted disabling the mods I added, but the issue persists, so I'm unsure if they are the cause or not.

**Comment by trulyno** [comment]
This is a GregTech bug that has existed for almost an year. I cannot fix it
