### ISSUE TITLE
Cobblework recipe conflict for gravel and sand

### ISSUE THREAD

**Issue by Caerglad** [trulyno/star-technology#54]
Recipe for 2048 Sand and 512 Gravel in Large Sieve Cobbleworks share same circuit number

![image](https://github.com/trulyno/star-technology/assets/1807505/7a392c37-2077-49d2-b8e8-52216d3cd05f)

![image](https://github.com/trulyno/star-technology/assets/1807505/e534597d-de88-4f83-90fd-17f7a557aa89)

**Comment by KgNDK** [comment]
@Caerglad Which version of the pack are you using? This is fixed in hotfix 4.
![image](https://github.com/trulyno/star-technology/assets/42304902/57a12473-d47d-433b-9c8f-77e0510e2863)
![image](https://github.com/trulyno/star-technology/assets/42304902/7fd69341-b47f-4cf1-bddb-26b201d407d4)

**Comment by Caerglad** [comment]
Ok, my bad. It's just a cosmetic issue with NC tag obscuring top part of the number
