### ISSUE TITLE
using a wrench on a huge diesel sometimes crashes the game

### ISSUE THREAD

**Issue by MrCauli** [trulyno/star-technology#58]
I used the _create_ wrench on the _create diesel generators_ huge diesel engine to make the pipe connect to it (the pipe was already in position to connect), and it sometimes crashed my game. I believe no progress was lost, and the connection went through (it was there when I relaunched). I don't know what causes it, but it happened twice on the same block (I undid the connection and redid it).
Now I've wrenched diesel engines on the other side of the pipe and there was no crash, so it might have something to do with the pipes getting updated and not liking it.
edit: putting in a shaft into the diesel about to run crashed the game.

**Comment by Caerglad** [comment]
I'm not able to reproduce it on new version
