### ISSUE TITLE
3 Mod Tooltips

### ISSUE THREAD

**Issue by NatiM6** [trulyno/star-technology#60]
There are mods that add 3 mod tooltips. How did that happen.

**Comment by NatiM6** [comment]
![very minecrafty stick](https://github.com/trulyno/star-technology/assets/29282012/2a243f03-5969-4b83-9159-9a0019a62a2e)

**Comment by Nt45Dev** [comment]
Having the same issue. I've noticed some have 2 of a mod and 1 of a different mod such as KubeJS

**Comment by Caerglad** [comment]
Looks to be fixed in 1.20.1 version of the pack, so closing it now.
![image](https://github.com/user-attachments/assets/6ce8161d-cf46-4309-a24f-a8082e25b566)
![image](https://github.com/user-attachments/assets/e84be233-7c50-4d26-968e-361f26405725)
