### ISSUE TITLE
Spelling mistake in the Aqueous Accumulator task description

### ISSUE THREAD

**Issue by Salt101nasr** [trulyno/star-technology#61]
The spelling mistake in question is the word next being misspelled as "noxt"
![Screenshot from 2024-07-04 22-46-01](https://github.com/trulyno/star-technology/assets/174752681/21a43751-30dd-4433-9ff3-dc013eddb06a)

**Comment by trulyno** [comment]
No longer relevant as quests are reworked from the ground up
