### ISSUE TITLE
Custom recipes broken

### ISSUE THREAD

**Issue by jetchg** [trulyno/star-technology#62]
When I attempt to make wrought iron or glass in the campfire, it will not place, and the recipe would not show in JEI. If I look on how to get sulfur, it is impossible to make in ULV. How can I fix this?

**Comment by Caerglad** [comment]
Campfire recipes are working as intended 
![image](https://github.com/user-attachments/assets/f1d568bc-846b-4c3a-8a87-bd54b5ad1049)

You can get tiny pile of sulfur from sieving or regular one from processing ores in kinetic ore factory
