### ISSUE TITLE
3 Mod Tooltips Fix

### ISSUE THREAD

**Issue by winterSteve25** [trulyno/star-technology#63]
As outlined in #60 there are 3 mod tooltips over items. Through my testing this can be fixed by removing the ModNameTooltip mod and by modifying the following field in the jade config at `config/jade/jade.json` to `"itemModNameTooltip": false`

**Comment by BlazeHunterVN1610** [comment]
You can just remove Mod Name Tooltip, since Jade added the tooltip for item already

**Comment by winterSteve25** [comment]
> You can just remove Mod Name Tooltip, since Jade added the tooltip for item already
> edit: In EMI config, there is an option for adding mod tooltip, you can turn it off (or just remove EMI, it doesn't have that too much impact), combine with removing Mod Name Tooltip, you will have only 1 tooltip

Yea the idea is that there are 3 mods doing the same thing removing any of the 2 will get rid of the issue

**Comment by ssoaper** [comment]
EMI's tooltips are the most useful as they work with fluids, so the logical solution is disabling the Jade tooltip and removing the Mod Name Tooltip mod.

**Comment by Caerglad** [comment]
As mentioned in #60 it seems to be fixed in 1.20.1 version of the pack
