### ISSUE TITLE
[suggestion] add additional fuels to Create low burners

### ISSUE THREAD

**Issue by Ylexak** [trulyno/star-technology#66]
Would there be a possibility to add a Lava bucket as a fuel source for the create low burners. the burner would use the lava while leaving the bucket inside until its taken out manually or automatically
<img width="1440" alt="Screenshot_2024-07-10_at_4 03 55_pm" src="https://github.com/trulyno/star-technology/assets/174940065/abb7ed2c-7c99-4a88-8d29-686dec0d6171">

**Comment by trulyno** [comment]
Not possible. Ask the mod author, not here.
