### ISSUE TITLE
Batch Composter has wrong recipe or output

### ISSUE THREAD

**Issue by dminikm** [trulyno/star-technology#67]
The Batch Composter from Thermal Series is listed in EMI as composting various materials into bonemeal. However, it will actually output the Compost item (also from Thermal).

Either the recipe in EMI is wrong and it should show as outputting Compost. Or the output is wrong an it should output bonemeal instead.

**Comment by ssoaper** [comment]
This is intended behavior and is not actually an issue.

**Comment by dminikm** [comment]
@ssoaper I'm not sure I understand.

When you search for the Batch Composter and look into the recipes, you can see that it's listed as composting into bonemeal (note the batch composter on the bottom):
![image](https://github.com/user-attachments/assets/3459a811-1abc-47b6-b5cb-a26a6ea41add)

But, using the composter yields compost:
![image](https://github.com/user-attachments/assets/f045503b-0c2e-48da-ad4e-938809c64de3)

The compost item doesn't even have an associated recipe in EMI. If you click on it, nothing happens.

Now, I can get the composter making the compost item. But in that case, the EMI recipes are wrong. On the other hand, if the EMI recipe is how it's supposed to be then the batch composter is not working correctly.

**Comment by ssoaper** [comment]
The recipes are wrong due to EMI beautifying the recipes and adding a diagram. it normally says 'compostable' in JEI. If you want this issue fixed consider asking elsewhere as the issue is an EMI/Thermal bug. The batch composter is working as intended.

**Comment by LeDiablePatate** [comment]
This is EMI's way of showing things. For JEI, it just shows what can be composted and at what chance. The Thermal Series devs propably didn't think a lot about it and just made it so that the batch composter's recipes are the same as the vanilla composter.

**Comment by dminikm** [comment]
I see. I'll close this since it's not a issue specific to this pack.
Might be worth it to mention that in one of the bonemeal/composter quests though.

Thanks for the explaination.
