### ISSUE TITLE
Thermal Soul Infused Ingot not compatible with GTCEU ingot

### ISSUE THREAD

**Issue by Schrubbls** [trulyno/star-technology#7]
![image](https://github.com/trulyno/star-technology/assets/8899590/8b240884-f95f-45c9-b699-377dfd29c782)

item smelts into thermal extra ingot which is useless,

![image](https://github.com/trulyno/star-technology/assets/8899590/edd152bd-7a29-44f0-9068-d416d3a45bf9)

thats my hack fix because i dont find the smelting recipe

**Comment by trulyno** [comment]
Fixed in latest
