### ISSUE TITLE
Bulk Blasting items can be destroyed if not picked up and user quits the game and relogs in

### ISSUE THREAD

**Issue by postie77** [trulyno/star-technology#75]
Steps to reproduce:

1. Put an item on a depot in a bulk blasting setup (for example, crushed copper ore)
2. Wait until the ore is cooked into an ingot
3. Quit the game
4. Reopen the game
5. The ingot will start cooking again and be destroyed.

**Comment by LeDiablePatate** [comment]
Please submit that to the Create devs and not here

**Comment by LeDiablePatate** [comment]
Because this is probably not coming from the modpack

**Comment by postie77** [comment]
Happy for this to be closed if it's Create mod that's the issue :)

**Comment by LeDiablePatate** [comment]
Have you tried throwing the ingots into the blasting ? If they disappear, then that means that reloading the world makes the items think they are being smelted, instead of finished being smelted

**Comment by bloodscon** [comment]
https://github.com/cech12/WoodenBucket/issues/19

**Comment by bloodscon** [comment]
It's a create / minecraft thing when you log out it resets the entity data and anything in a create bulk blast system that has no smelt recipe will be destroyed

**Comment by postie77** [comment]
Fair enough. If it's the Create mod, this isn't the right place to raise. it. I'll close it.
