### ISSUE TITLE
Cannot view multiblock data

### ISSUE THREAD

**Issue by FakeSiryakari** [trulyno/star-technology#76]
when trying to view any multiblock help, "missing pages" appears
![obrazek](https://github.com/user-attachments/assets/3e16f800-0fb7-4236-b14b-66163c517e4b)

**Comment by LeDiablePatate** [comment]
The GT in game guide has not been fully implemented in this version of GT

**Comment by LeDiablePatate** [comment]
To view how to make the multiblocks, use JEI on the controller of the multiblock you are trying to make

**Comment by Caerglad** [comment]
Closing, as thats GT issue. It may be added to the pack after update to newer minecraft version and when it's implemented in GT
