### ISSUE TITLE
Kinetic Sieve possibly broken, no multiblock guide 

### ISSUE THREAD

**Issue by Arri2234** [trulyno/star-technology#78]
about an hour spent, I have 8192 su going at 128 rpm with both input and output busses that are LV, and no program circuit works, am I missing something or is the Kinetic Sieve just broken?

**Comment by LeDiablePatate** [comment]
Look at the number of outputs that sand and gravel recipes give

**Comment by Golas-123** [comment]
I've tried everything possible and still not working, even whit a creative motor
and a lot of expensive outputs

**Comment by Golas-123** [comment]
Forget it, i didnt put the mesh.
