### ISSUE TITLE
No recipe for a crafting table

### ISSUE THREAD

**Issue by Blees-o-tron** [trulyno/star-technology#9]
The recipe in JEI for the crafting table is blank. When you hit the button to transfer the recipe to your 2x2 grid, nothing is moved.

Additionally, and this may be related: if you put any items in the 2x2 craft grid, then remove them all, the output is 2 Brass Bolt from Gregtech. This item also has a blank crafting recipe in JEI.

Currently on BETA 2 HOTFIX 2 from Curseforge.

EDIT:
Creative Mode'd myself a crafting table, but then the crafting table had a different blank-recipe'd item given for free when you remove items from it. I also noticed that oak planks have two recipes. An oak log gives 6 planks, but a blank recipe gives 4.

**Comment by trulyno** [comment]
We've been experiencing this for a couple of updates already. I don't know what causes this, but the most random actions seem to fix it(reloading, removing a mod, etc.). It doesn't happen I'm dev, it's only on imported profiles. I'll try to find the cause. Any help is appreciated 👍

**Comment by trulyno** [comment]
The addition of Load My F***ing Tags and a quest for reloading the eworld just in case should have fixed it
