### ISSUE TITLE
Render crash with effortless building

### ISSUE THREAD

**Issue by Pedgux** [trulyno/star-technology#91]
I was just using the mod to ease out the early block placing, when doing the gravel -> ores sieving thing. then boom crash. 

Crash log: [crash-2024-08-23_21.17.29-client.txt](https://github.com/user-attachments/files/16732436/crash-2024-08-23_21.17.29-client.txt)

**Comment by Caerglad** [comment]
It looks more like something on effortless building devs side, not the modpack issue.

From my side only crashes I got was placing a lot of blocks while playing on a server and reaching limit of max packet size.
