### ISSUE TITLE
Crash, and then Crash-on-startup, in SimpleKineticElectricWorkableMachine from GTCE when interacting with AE2

### ISSUE THREAD

**Issue by stephen-smith** [trulyno/star-technology#92]
Another player on the same server was running some AE2 cabling (probably fluix glass cable) near a "gearbox", and the server crashed, and now it crashes on startup as well.  Probably going to have to restore from backup.

[latest.log](https://github.com/user-attachments/files/16740972/latest.log) attached, has a pretty good stack trace.

**Comment by stephen-smith** [comment]
Looks like GT has a fix:  GregTechCEu/GregTech-Modern#1407 HTH

**Comment by trulyno** [comment]
GTM 1.19.2 is abandoned by its devs. No fix can be applied.
