### ISSUE TITLE
Kinetic Sieve EMI description is either wrong or I am not doing it correctly.

### ISSUE THREAD

**Issue by W4tch3rTheSecond** [trulyno/star-technology#93]
In the recipe it says it takes 90s to turn 256 graven into resources, but in-game it actually takes ~180s Doesn't matter what speed the kinetic input has.

**Comment by LeDiablePatate** [comment]
Would you mind illustrating with pictures ?

**Comment by W4tch3rTheSecond** [comment]
I think we figured it out, seems the server is running on 10 ticks per second instead of the usual 20 so everything takes twice as long. 

Sorry for the inconvenience.
