### ISSUE TITLE
[Mod Suggestion for 1.20.1 Alpha] Modern AE2 Additions

### ISSUE THREAD

**Issue by OfficialZygorg** [trulyno/star-technology#94]
https://www.curseforge.com/minecraft/mc-mods/modern-ae2-additions

It adds: (Copied from the mod page to save a click):

- Pattern P2P Tunnel - Allows one pattern provider to provide to multiple machines at once by connecting it to the input of the tunnel. Additionally the output tunnel links back to the pattern provider to allow Molecular Assemblers to work easily.

- EU P2P Tunnel - Transfers EU from GregTech-Modern. Taxes the EU at the same rate other P2P tunnel transfers are taxed.

- Dense Co-Processing Units - Crafting CPU Co-Processing Units that provide more than 1 thread. One for each storage component giving as many threads as there are kilobytes in the component (so 4, 16, 64, 256 threads respectively.

- Multi P2P Tunnels - P2P Tunnels with multiple inputs, not much else really. Due to how its implemented, they're seperate parts and won't automatically work with custom P2Ps added by other mods (though AE2's P2Ps have them added by me)

(Basically, this mod is a huge QoL for parallelizing machines, transfer EU GT power through the AE network, better co-processing units, to not spam the single ones, and P2Ps with multi-inputs (Ex: If you have multiple setups for oxigen, you can have em to the input)).

**Comment by trulyno** [comment]
Some of it's features will be present in the 1.20.1 port.
