### ISSUE TITLE
Kinetic Ore Factory is not working 

### ISSUE THREAD

**Issue by KasimirHoff** [trulyno/star-technology#96]
Hi, my ore Factory will not work. The whole setup uses LV parts and its build like shown in JEI. Any conclusions?

**Comment by Alehopper** [comment]
Hey, is the right amount of Output Space available?

**Comment by KasimirHoff** [comment]
there are 4 slots in the output Bus

**Comment by KasimirHoff** [comment]
sadly not the problem

**Comment by Caerglad** [comment]
Is multiblock forming?

**Comment by KasimirHoff** [comment]
yea

**Comment by KasimirHoff** [comment]
<img width="352" alt="Screenshot 2024-09-06 183219" src="https://github.com/user-attachments/assets/722d054b-7a13-472e-bc6f-85086655fc0e">

**Comment by KasimirHoff** [comment]
the kinetic box says 256su

**Comment by Alehopper** [comment]
Not su, rpm

**Comment by KasimirHoff** [comment]
oh mb its only 8rpm
