### ISSUE TITLE
Electrico-Kinetic Ore Factory refuses to assemble

### ISSUE THREAD

**Issue by ahi6** [trulyno/star-technology#97]
We tried building the multiblock, and even after checking it multiple times, it refuses to assemble and says it's an invalid structure. We even tried to build it in creative mode just like it is in JEI to no avail. Is there a reason why that's the case?

Here are some screenshots of the multiblock:
![2024-09-06_22 27 24](https://github.com/user-attachments/assets/873981b0-1e38-4bf7-81f0-d20e8b2e946c)
![2024-09-06_22 27 30](https://github.com/user-attachments/assets/657a4c17-315b-4912-8152-ca118a7f1094)
![2024-09-06_22 27 42](https://github.com/user-attachments/assets/db8af8da-dce0-4a15-8e2c-993680469745)
![2024-09-06_22 28 31](https://github.com/user-attachments/assets/4316aa78-1135-486a-be96-2e26ee6746dd)
![2024-09-06_22 28 49](https://github.com/user-attachments/assets/def3e52b-ff09-46da-9314-7399165427d0)

(looking at Reddit, it seems like I am [not the only person with this issue](https://www.reddit.com/r/feedthebeast/comments/1eakh4s/i_am_playing_the_star_tech_modpack_and_got_stuck/))

**Comment by Alehopper** [comment]
wrong type of machine casing, need solid, without steel

**Comment by ahi6** [comment]
The machine is now working. Thank you!
